Import Library

In [ ]:
import pandas as pd

import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.metrics import accuracy_score, classification_report, mean_squared_error

from sklearn.linear_model import LogisticRegression, LinearRegression

#from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier#, RandomForestRegressor

Import Data

In [2]:
data_media = pd.read_csv('Media.csv')
print(data_media.info())
data_media.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 25 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   อาชีพ_ข้าราชการ                                                            167 non-null    float64
 1   อาชีพ_ธุรกิจส่วนตัว                                                        167 non-null    float64
 2   อาชีพ_นักศึกษา                                                             167 non-null    float64
 3   อาชีพ_นักเรียน                                                             167 non-null    float64
 4   อาชีพ_พนักงานบริษัทเอกชน                                                   167 non-null    float64
 5   อาชีพ_พนักงานมหาวิทยาลัย                                                   167 non-null    float64
 6   อาชีพ_พนักงานรัฐวิสาหกิจ                                                   167 non-null    float64
 7   อาชีพ_ฟรีแลนซ์/อาชีพอิสระ                                                  167 non-null    float64
 8   อาชีพ_ว่างงาน                                                              167 non-null    float64
 9   อาชีพ_แพทย์                                                                167 non-null    float64
 10  อาชีพ_แม่ค้า                                                               167 non-null    float64
 11  อาชีพ_ไลฟ์สด                                                               167 non-null    float64
 12  เพศ_ชาย                                                                    167 non-null    float64
 13  เพศ_หญิง                                                                   167 non-null    float64
 14  เพศ_ไม่ระบุ                                                                167 non-null    float64
 15  ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ใช้น้อยกว่าปกติ         167 non-null    float64
 16  ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ใช้มากกว่าปกติ          167 non-null    float64
 17  ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ใช้เท่าเดิม             167 non-null    float64
 18  ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ไม่ใช้โซเชียลมีเดียเลย  167 non-null    float64
 19  Cluster_ID_0                                                               167 non-null    float64
 20  Cluster_ID_1                                                               167 non-null    float64
 21  Cluster_ID_2                                                               167 non-null    float64
 22  อายุ                                                                       167 non-null    int64
 23  ความถี่ในการเปิดรับสื่อในแต่ละช่องทางต่อสัปดาห์ [ออนไลน์]                  167 non-null    int64
 24  ระยะเวลาในการเสพสื่อต่อวัน ในแต่ละช่องทาง [ออนไลน์]                        167 non-null    int64
dtypes: float64(22), int64(3)
memory usage: 32.7 KB
None

,อาชีพ_ข้าราชการ,อาชีพ_ธุรกิจส่วนตัว,อาชีพ_นักศึกษา,อาชีพ_นักเรียน,อาชีพ_พนักงานบริษัทเอกชน,อาชีพ_พนักงานมหาวิทยาลัย,อาชีพ_พนักงานรัฐวิสาหกิจ,อาชีพ_ฟรีแลนซ์/อาชีพอิสระ,อาชีพ_ว่างงาน,อาชีพ_แพทย์,...,ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ใช้น้อยกว่าปกติ,ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ใช้มากกว่าปกติ,ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ใช้เท่าเดิม,ในวันหยุดยาวหรือเทศกาล คุณใช้โซเชียลมีเดีย อย่างไร_ไม่ใช้โซเชียลมีเดียเลย,Cluster_ID_0,Cluster_ID_1,Cluster_ID_2,อายุ,ความถี่ในการเปิดรับสื่อในแต่ละช่องทางต่อสัปดาห์ [ออนไลน์],ระยะเวลาในการเสพสื่อต่อวัน ในแต่ละช่องทาง [ออนไลน์]
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1,2,2
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1,3,3
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1,3,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2,3,2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1,3,1

In [3]:
data_period = pd.read_csv('Period.csv')
print(data_period.info())
data_period.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 73 columns):
 #   Column                                                                                                                                                                                                                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                     --------------  -----
 0   อาชีพ_ข้าราชการ                                                                                                                                                                                                                                                                                                            167 non-null    float64
 1   อาชีพ_ธุรกิจส่วนตัว                                                                                                                                                                                                                                                                                                        167 non-null    float64
 2   อาชีพ_นักศึกษา                                                                                                                                                                                                                                                                                                             167 non-null    float64
 3   อาชีพ_นักเรียน                                                                                                                                                                                                                                                                                                             167 non-null    float64
 4   อาชีพ_พนักงานบริษัทเอกชน                                                                                                                                                                                                                                                                                                   167 non-null    float64
 5   อาชีพ_พนักงานมหาวิทยาลัย                                                                                                                                                                                                                                                                                                   167 non-null    float64
 6   อาชีพ_พนักงานรัฐวิสาหกิจ                                                                                                                                                                                                                                                                                                   167 non-null    float64
 7   อาชีพ_ฟรีแลนซ์/อาชีพอิสระ                                                                                                                                                                                                                                                                                                  167 non-null    float64
 8   อาชีพ_ว่างงาน                                                                                                                                                                                                                                                                                                              167 non-null    float64
 9   อาชีพ_แพทย์                                                                                                                                                                                                                                                                                                                167 non-null    float64
 10  อาชีพ_แม่ค้า                                                                                                                                                                                                                                                                                                               167 non-null    float64
 11  อาชีพ_ไลฟ์สด                                                                                                                                                                                                                                                                                                               167 non-null    float64
 12  เพศ_ชาย                                                                                                                                                                                                                                                                                                                    167 non-null    float64
 13  เพศ_หญิง                                                                                                                                                                                                                                                                                                                   167 non-null    float64
 14  เพศ_ไม่ระบุ                                                                                                                                                                                                                                                                                                                167 non-null    float64
 15  province_กรุงเทพมหานคร                                                                                                                                                                                                                                                                                                     167 non-null    float64
 16  province_ขอนแก่น                                                                                                                                                                                                                                                                                                           167 non-null    float64
 17  province_ฉะเชิงเทรา                                                                                                                                                                                                                                                                                                        167 non-null    float64
 18  province_ชลบุรี                                                                                                                                                                                                                                                                                                            167 non-null    float64
 19  province_นครปฐม                                                                                                                                                                                                                                                                                                            167 non-null    float64
 20  province_นครราชสีมา                                                                                                                                                                                                                                                                                                        167 non-null    float64
 21  province_นครศรีธรรมราช                                                                                                                                                                                                                                                                                                     167 non-null    float64
 22  province_นนทบุรี                                                                                                                                                                                                                                                                                                           167 non-null    float64
 23  province_ปทุมธานี                                                                                                                                                                                                                                                                                                          167 non-null    float64
 24  province_ภูเก็ต                                                                                                                                                                                                                                                                                                            167 non-null    float64
 25  province_ร้อยเอ็ด                                                                                                                                                                                                                                                                                                          167 non-null    float64
 26  province_ลพบุรี                                                                                                                                                                                                                                                                                                            167 non-null    float64
 27  province_ลำพูน                                                                                                                                                                                                                                                                                                             167 non-null    float64
 28  province_สงขลา                                                                                                                                                                                                                                                                                                             167 non-null    float64
 29  province_สมุทรปราการ                                                                                                                                                                                                                                                                                                       167 non-null    float64
 30  province_สมุทรสาคร                                                                                                                                                                                                                                                                                                         167 non-null    float64
 31  province_อุบลราชธานี                                                                                                                                                                                                                                                                                                       167 non-null    float64
 32  province_เชียงใหม่                                                                                                                                                                                                                                                                                                         167 non-null    float64
 33  province_แพร่                                                                                                                                                                                                                                                                                                              167 non-null    float64
 34  คุณดื่มกาแฟประเภทใดบ่อยที่สุด_กาแฟผงสำเร็จรูป                                                                                                                                                                                                                                                                              167 non-null    float64
 35  คุณดื่มกาแฟประเภทใดบ่อยที่สุด_กาแฟผงสำเร็จรูปพร้อมดื่ม (3-in-1)                                                                                                                                                                                                                                                            167 non-null    float64
 36  คุณดื่มกาแฟประเภทใดบ่อยที่สุด_กาแฟพร้อมดื่ม (Ready to drink)                                                                                                                                                                                                                                                               167 non-null    float64
 37  คุณดื่มกาแฟประเภทใดบ่อยที่สุด_กาแฟสดคั่วบด เช่น ร้านกาแฟสด                                                                                                                                                                                                                                                                 167 non-null    float64
 38  คุณดื่มกาแฟประเภทใดบ่อยที่สุด_แคปซูลกาแฟ                                                                                                                                                                                                                                                                                   167 non-null    float64
 39  คุณดื่มกาแฟประเภทใดบ่อยที่สุด_ไม่ดื่มกาแฟประเภทใดเลย                                                                                                                                                                                                                                                                       167 non-null    float64
 40  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_nan                                                                                                                                                                                                                                        167 non-null    float64
 41  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มทดแทนเมื่อหาร้านกาแฟสดไม่ได้                                                                                                                                                                                                           167 non-null    float64
 42  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มทดแทนเมื่อหาร้านกาแฟสดไม่ได้, ดื่มก่อนไปปาร์ตี้กับเพื่อน                                                                                                                                                                               167 non-null    float64
 43  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มระหว่างทำงานอดิเรกต่างๆ เช่น ดูซีรีส์, เล่นเกม, ดูบอล                                                                                                                                                                                  167 non-null    float64
 44  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มระหว่างเดินทาง/ขับรถ                                                                                                                                                                                                                   167 non-null    float64
 45  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มระหว่างเดินทาง/ขับรถ, ดื่มทดแทนเมื่อหาร้านกาแฟสดไม่ได้                                                                                                                                                                                 167 non-null    float64
 46  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน                                                                                                                                                                                                      167 non-null    float64
 47  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน, ดื่มทดแทนเมื่อหาร้านกาแฟสดไม่ได้                                                                                                                                                                    167 non-null    float64
 48  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน, ดื่มระหว่างทำงานอดิเรกต่างๆ เช่น ดูซีรีส์, เล่นเกม, ดูบอล                                                                                                                                           167 non-null    float64
 49  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน, ดื่มระหว่างเดินทาง/ขับรถ                                                                                                                                                                            167 non-null    float64
 50  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน, ดื่มให้ไม่ง่วงในคืนอ่านหนังสือสอบ                                                                                                                                                                   167 non-null    float64
 51  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน, ดื่มให้ไม่ง่วงในวันที่ทำงานดึก, ดื่มระหว่างเดินทาง/ขับรถ, ดื่มระหว่างมื้ออาหาร แทนเครื่องดื่มอื่นๆ เช่น ชานม, ดื่มให้ไม่ง่วงในคืนอ่านหนังสือสอบ                                                     167 non-null    float64
 52  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน, ดื่มให้ไม่ง่วงในวันที่ทำงานดึก, ดื่มให้ไม่ง่วงในคืนอ่านหนังสือสอบ                                                                                                                                   167 non-null    float64
 53  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวในตอนเช้า                                                                                                                                                                                                                    167 non-null    float64
 54  คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวในตอนเช้า, ดื่มทดแทนเมื่อหาร้านกาแฟสดไม่ได้                                                                                                                                                                                  167 non-null    float64

,อาชีพ_ข้าราชการ,อาชีพ_ธุรกิจส่วนตัว,อาชีพ_นักศึกษา,อาชีพ_นักเรียน,อาชีพ_พนักงานบริษัทเอกชน,อาชีพ_พนักงานมหาวิทยาลัย,อาชีพ_พนักงานรัฐวิสาหกิจ,อาชีพ_ฟรีแลนซ์/อาชีพอิสระ,อาชีพ_ว่างงาน,อาชีพ_แพทย์,...,"คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวในตอนเช้า, ดื่มให้ตื่นตัวระหว่างทำงานเวลากลางวัน, ดื่มให้ไม่ง่วงในวันที่ทำงานดึก, ดื่มระหว่างเดินทาง/ขับรถ","คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ตื่นตัวในตอนเช้า, ดื่มให้ไม่ง่วงในวันที่ทำงานดึก, ดื่มทดแทนเมื่อหาร้านกาแฟสดไม่ได้",คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ไม่ง่วงในวันที่ทำงานดึก,"คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ดื่มให้ไม่ง่วงในวันที่ทำงานดึก, ดื่มระหว่างเดินทาง/ขับรถ",คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ไม่ดื่มกาแฟ Ready to drink เลย,"คุณดื่มกาแฟพร้อมดื่ม (Ready to drink) ในโอกาส/โมเมนต์ใดบ้าง (เลือกได้หลายคำตอบ)_ไม่ดื่มกาแฟ Ready to drink เลย, เมื่อมีมาแจกให้ทดลองดื่ม",Cluster_ID_0,Cluster_ID_1,Cluster_ID_2,อายุ
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1

predict customer segment

In [17]:
data_media['customer_segment'] = np.argmax(data_media[['Cluster_ID_0' , 'Cluster_ID_1' , 'Cluster_ID_2']].values , axis=1)
target = 'customer_segment'

feature_cs = ['อาชีพ_ข้าราชการ' , 'อาชีพ_ธุรกิจส่วนตัว','อาชีพ_นักศึกษา','อาชีพ_พนักงานบริษัทเอกชน','อาชีพ_พนักงานรัฐวิสาหกิจ','อาชีพ_ฟรีแลนซ์/อาชีพอิสระ','อาชีพ_ว่างงาน','อาชีพ_แพทย์','อาชีพ_แม่ค้า','อาชีพ_ไลฟ์สด'  ,'เพศ_ชาย' ,'เพศ_หญิง','เพศ_ไม่ระบุ' , 'อายุ']

X = data_media[feature_cs]
y = data_media[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
#Logistic Regression

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

y_pred_log = log_model.predict(X_test_scaled)

print("Logistic Regression")
print("Accuracy :", accuracy_score(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

Logistic Regression
Accuracy : 0.6176470588235294
              precision    recall  f1-score   support

           0       0.62      0.90      0.73        20
           1       0.00      0.00      0.00         3
           2       0.75      0.27      0.40        11

    accuracy                           0.62        34
   macro avg       0.46      0.39      0.38        34
weighted avg       0.61      0.62      0.56        34

predict platform

In [20]:
feature_p = ['อาชีพ_ข้าราชการ' , 'อาชีพ_ธุรกิจส่วนตัว','อาชีพ_นักศึกษา','อาชีพ_พนักงานบริษัทเอกชน','อาชีพ_พนักงานรัฐวิสาหกิจ','อาชีพ_ฟรีแลนซ์/อาชีพอิสระ','อาชีพ_ว่างงาน','อาชีพ_แพทย์','อาชีพ_แม่ค้า','อาชีพ_ไลฟ์สด'  ,'เพศ_ชาย' ,'เพศ_หญิง','เพศ_ไม่ระบุ' , 'อายุ' , 'ความถี่ในการเปิดรับสื่อในแต่ละช่องทางต่อสัปดาห์ [ออนไลน์]',	'ระยะเวลาในการเสพสื่อต่อวัน ในแต่ละช่องทาง [ออนไลน์]']

X = data_media[feature_p]
y = data_media[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("Random Forest")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest
Accuracy: 0.5294117647058824
              precision    recall  f1-score   support

           0       0.62      0.75      0.68        20
           1       0.33      0.33      0.33         3
           2       0.29      0.18      0.22        11

    accuracy                           0.53        34
   macro avg       0.41      0.42      0.41        34
weighted avg       0.49      0.53      0.50        34

predict time to ads